[workspace]
members = [
	"utils",
	"server",
	"application",
	"clients/desktop", 
]
resolver = "2"

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
panic = "abort"
strip = true

[workspace.dependencies]
utils = { path = "utils" }
application = { path = "application" }

tokio         = { version = "1", features = ["fs", "signal"] }
tokio-scoped = "0.2.0"
tokio-tungstenite = "0.29.0"
futures-util = "0.3.32"

serde         = { version = "1", features = ["derive"] }
serde_json    = "1"

uuid = { version = "1.24.0", default-features = false, features = ["std", "v7"] }
automerge = "0.9.0"
